### PR TITLE
Resolve windows 3.8 issue

### LINKED ISSUE #94: Windows Latest on Python 3.8 Constantly Fails
For some reason, Windows-2022 is now failing for me on Python 3.8 only:

```
Run snok/install-poetry@v[1](https://github.com/adam-grant-hendry/qtpygraph/actions/runs/3202205327/jobs/5230946943#step:6:1).3.2
Run $GITHUB_ACTION_PATH/main.sh

Setting Poetry installation path as C:/Users/runneradmin/AppData/Roaming/Python/Scripts

Installing Poetry 👷

Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

C:\Users\runneradmin\AppData\Roaming\Python\Scripts\bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.2.1)
Installing Poetry (1.2.1): Creating environment
Installing Poetry (1.2.1): An error occurred. Removing partial environment.
Traceback (most recent call last):
  File "C:/Users/RUNNER~1/AppData/Local/Temp/tmp.0IGyZ1qQC7", line 9[40](https://github.com/adam-grant-hendry/qtpygraph/actions/runs/3202205327/jobs/5230946943#step:6:42), in <module>
    sys.exit(main())
  File "C:/Users/RUNNER~1/AppData/Local/Temp/tmp.0IGyZ1qQC7", line 919, in main
    return installer.run()
  File "C:/Users/RUNNER~1/AppData/Local/Temp/tmp.0IGyZ1qQC7", line 550, in run
    self.install(version)
  File "C:/Users/RUNNER~1/AppData/Local/Temp/tmp.0IGyZ1qQC7", line 571, in install
    with self.make_env(version) as env:
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:/Users/RUNNER~1/AppData/Local/Temp/tmp.0IGyZ1qQC7", line 643, in make_env
    raise e
  File "C:/Users/RUNNER~1/AppData/Local/Temp/tmp.0IGyZ1qQC7", line 629, in make_env
    yield VirtualEnvironment.make(env_path)
  File "C:/Users/RUNNER~1/AppData/Local/Temp/tmp.0IGyZ1qQC7", line 319, in make
    builder.create(target)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\venv\__init__.py", line 68, in create
    self._setup_pip(context)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\venv\__init__.py", line 289, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\subprocess.py", line [41](https://github.com/adam-grant-hendry/qtpygraph/actions/runs/3202205327/jobs/5230946943#step:6:43)5, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\subprocess.py", line [49](https://github.com/adam-grant-hendry/qtpygraph/actions/runs/3202205327/jobs/5230946943#step:6:51)3, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\subprocess.py", line 8[58](https://github.com/adam-grant-hendry/qtpygraph/actions/runs/3202205327/jobs/5230946943#step:6:60), in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\hostedtoolcache\windows\Python\3.8.10\x[64](https://github.com/adam-grant-hendry/qtpygraph/actions/runs/3202205327/jobs/5230946943#step:6:66)\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by sondrelg**
Adds the Python matrix to the non-default settings test. This would have uncovered the issue from #94. Then it resolves #94 by avoiding the official installation script for Windows targets. 

A few things to consider:
- It would have been nice to limit the logic to Windows for Python <= 3.8, but we cannot reliably know what Python version is active, can we? I believe using `setup-python` after this action works most of the time, if not all of the time.
- This just reverts to the old installation script. Are there any reasons to consider using a newer version of it?

### CODE REVIEW

**Comment by sondrelg** [comment]
@miigotu looking at the poetry upstream issue, they recommend using powershell (default windows shell) instead of bash. Perhaps we should spend a little effort looking into whether we can create an ergonomic way of setting up an os-matrix with powershell as the shell for windows.

We could even go as far as outputting specific errors for windows bash users, telling them to switch to powershell on python 3.7 and 3.8, though perhaps that should be considered a breaking change. 

Just thinking out loud 🤔

**Comment by miigotu** [comment]
I think we should support both methods. I can look a bit at it later, tonight.

I do have a huge project coming up (with a new developer joining) on sickchill. Rewriting the entire UI with jinja2, webpack, reactjs, and a flask backend on top of reorganizing the entire user flow for shows and settings.

So I'll be on to get a wire frame up for him and take a look at poetry PowerShell.

**Comment by sondrelg** [comment]
Yeah it now seems like the bash bug could be fixed, so yeah sounds better to support both. Maybe we should merge this in the meantime to fix v1

**Comment by miigotu** [comment]
Yes I believe so. And maybe a refactor to support both bash, cmd, and PowerShell should be a major version bump, even though any shell they have set should work then.

**Comment by miigotu** [comment]
Does the fix in 96 not work with the newest poetry installer script?

I'd much rather not pin an old installer, as there are a bunch of new configuration settings we can expose with it

File: main.sh [hunk 1]
```diff
@@ -3,7 +3,12 @@
 set -eo pipefail
 
 INSTALLATION_SCRIPT="$(mktemp)"
-curl -sSL https://install.python-poetry.org/ --output "$INSTALLATION_SCRIPT"
+
+if [ "${RUNNER_OS}" == "Windows" ]; then
```
Comment (miigotu) [inline main.sh:7]: I dislike this much lol, can we fix this another way to keep using the latest installer?

Comment (sondrelg) [reply main.sh:7]: This is what we were doing prior to v1.3.2, one week ago, so in that sense it's not a huge change; but I agree I would never accept this if we had been on the official installation script from the beginning.

As far as I can tell there isn't another way to do this, until the upstream bug is fixed; but I would consider this a temporary band-aid until that happens. Maybe we could even assist in that. It would just be nice to have this working on the `@v1` tag for windows users in the meantime.

Comment (miigotu) [reply main.sh:7]: I agree. Just need to fix it somehow after the release. Can you link the upstream issue?

Comment (sondrelg) [reply main.sh:7]: https://github.com/python-poetry/install.python-poetry.org/issues/46

Comment (sondrelg) [reply main.sh:12]: Opened an issue for powershell support, and one to remove the deprecated installation script. Will merge this now and release v1.3.3 👍
